### ISSUE TITLE
[Suggestion/Feature Request] Banner/Background/Poster media downloaded for Plex

### ISSUE THREAD

**Issue by DeanAtEC** [DialmasterOrg/Youtarr#85]
I noticed in the Youtarr UI the channel images for each video and the channel itself are present, however, they are not in Plex. I see a few of them (most?) are downloaded alongside the videos. Are there plans to get those integrated/used by Plex? Or perhaps there is an issue on my setup and it's supposed to be working? No huge issue if so, just wanted to make sure I posted this before I forgot about it :)

**Comment by dialmaster** [comment]
If everything is working properly, then the video poster SHOULD be getting placed into the channel specific directory in your destination directory as "poster.jpg", which Plex should pick up and use.
The video metadata should be part of the written video file.

So, as an example, here is a video that youtarr recently placed in my destination directory, where my destination directory is D:\Youtube_2\

Downloading the video automatically added it to the channel subdirectory (Blitz) and created a directory under that for the video itself (Blitz - I Make RECORD Profit By Refining Oil - DcL5yxXcnkA)
So the video was written into:
D:\Youtube_2\Blitz\Blitz - I Make RECORD Profit By Refining Oil - DcL5yxXcnkA\

And in that directory I have 2 files that youtarr wrote:
Blitz - I Make RECORD Profit By Refining Oil  [DcL5yxXcnkA].mp4
and
poster.jpg

In Plex, that shows for me like this:
![image](https://github.com/user-attachments/assets/a2ff2a5d-88b4-467f-b891-3973135e6345)
and when I open that video it shows the metadata description from youtube because it is embedded into the video mp4:
![image](https://github.com/user-attachments/assets/1669ab4a-54ad-4225-ac14-0e17d0a6d9c1)

If this is not working the same way for you, then there may be another bug.

**Comment by DeanAtEC** [comment]
I think it might be on my side, on the Plex side of things. I see the files, and they are world readable, so I am not sure why Plex is not using them. I'll keep bashing away at Plex and close this as my issue not yours! :)

**Comment by DeanAtEC** [comment]
Closing as not an issue
